### ISSUE TITLE
Initializing `WebR` in react server components gives error "cannot determine runtime environment"

### ISSUE THREAD

**Issue by qiushiyan** [r-wasm/webr#171]
I have a nextjs [app](https://github.com/qiushiyan/nextjs-webr) that uses react server [components](https://github.com/qiushiyan/nextjs-webr/blob/main/src/app/page.tsx#L3-L5) to initialize a `WebR` object. I got an error "cannot determine runtime environment"

```
error - node_modules/.pnpm/@r-wasm+webr@0.1.0/node_modules/@r-wasm/webr/dist/webr.mjs (78:8) @ eval
error - Error: Cannot determine runtime environment
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/@r-wasm+webr@0.1.0/node_modules/@r-wasm/webr/dist/webr.mjs:81:11)
    at (sc_server)/./node_modules/.pnpm/@r-wasm+webr@0.1.0/node_modules/@r-wasm/webr/dist/webr.mjs (/Users/qiushi/workspace/tmp/next-webr/.next/server/app/page.js:1603:1)
    at __webpack_require__ (/Users/qiushi/workspace/tmp/next-webr/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./src/app/page.tsx:6:70)
    at (sc_server)/./src/app/page.tsx (/Users/qiushi/workspace/tmp/next-webr/.next/server/app/page.js:481:1)
    at Function.__webpack_require__ (/Users/qiushi/workspace/tmp/next-webr/.next/server/webpack-runtime.js:33:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collectGenerateParams (/Users/qiushi/workspace/tmp/next-webr/node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/utils.js:741:17) {
  type: 'Error',
  page: '/'
}
null
wait  - compiling...
event - compiled successfully in 81 ms (178 modules)
error - node_modules/.pnpm/@r-wasm+webr@0.1.0/node_modules/@r-wasm/webr/dist/webr.mjs (78:8) @ eval
error - Error: Cannot determine runtime environment
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/@r-wasm+webr@0.1.0/node_modules/@r-wasm/webr/dist/webr.mjs:81:11)
    at (sc_server)/./node_modules/.pnpm/@r-wasm+webr@0.1.0/node_modules/@r-wasm/webr/dist/webr.mjs (/Users/qiushi/workspace/tmp/next-webr/.next/server/app/page.js:1603:1)
    at __webpack_require__ (/Users/qiushi/workspace/tmp/next-webr/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./src/app/page.tsx:6:70)
    at (sc_server)/./src/app/page.tsx (/Users/qiushi/workspace/tmp/next-webr/.next/server/app/page.js:481:1)
    at Function.__webpack_require__ (/Users/qiushi/workspace/tmp/next-webr/.next/server/webpack-runtime.js:33:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collectGenerateParams (/Users/qiushi/workspace/tmp/next-webr/node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/utils.js:741:17) {
  type: 'Error',
  page: '/'
}
```

**Comment by georgestagg** [comment]
Thank you for the bug report. With the release of v0.1.1 of the `@r-wasm/webr` npm package, this should now hopefully work better.

I've put together a basic example of loading webR v0.1.1 into a Next.js application with an example repo at https://github.com/georgestagg/webr-nextjs-example. In the example webR is loaded as a server component in the file [app/page.tsx](https://github.com/georgestagg/webr-nextjs-example/blob/main/app/page.tsx).

Hopefully the updated npm package and the example repo helps you get up and running with webR. Please take a look and let me know if you have any further problems.

**Comment by qiushiyan** [comment]
Thank you!
