### ISSUE TITLE
New webr installs fail with module_not_found

### ISSUE THREAD

**Issue by jeroen** [r-wasm/webr#226]
I'm experiencing a strange bug that I have difficulty understanding.

As of a few days ago, new builds of my stack no longer work. I think npm fails to install some webr dependency. 

The strange thing is that it even fails when using older npm releases of webr that were working previously. I don't understand what has changed, the version of node and npm is the same.

Does the following trace give any hint which module it is that is missing?

```
cranlike    | node:internal/modules/cjs/loader:571
cranlike    |       throw e;
cranlike    |       ^
cranlike    |
cranlike    | Error: Cannot find module '/app/node_modules/@r-universe/webr/dist/webr.cjs'
cranlike    |     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1096:15)
cranlike    |     at finalizeEsmResolution (node:internal/modules/cjs/loader:1089:15)
cranlike    |     at resolveExports (node:internal/modules/cjs/loader:565:14)
cranlike    |     at Module._findPath (node:internal/modules/cjs/loader:634:31)
cranlike    |     at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
cranlike    |     at Module._load (node:internal/modules/cjs/loader:920:27)
cranlike    |     at Module.require (node:internal/modules/cjs/loader:1141:19)
cranlike    |     at require (node:internal/modules/cjs/helpers:110:18)
cranlike    |     at Object.<anonymous> (/app/node_modules/cranlike/routes/shared.js:5:12)
cranlike    |     at Module._compile (node:internal/modules/cjs/loader:1254:14)
cranlike    |     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
cranlike    |     at Module.load (node:internal/modules/cjs/loader:1117:32)
cranlike    |     at Module._load (node:internal/modules/cjs/loader:958:12)
cranlike    |     at Module.require (node:internal/modules/cjs/loader:1141:19)
cranlike    |     at require (node:internal/modules/cjs/helpers:110:18)
cranlike    |     at Object.<anonymous> (/app/node_modules/cranlike/app.js:16:20) {
cranlike    |   code: 'MODULE_NOT_FOUND',
cranlike    |   path: '/app/node_modules/@r-universe/webr/package.json'
cranlike    | }
cranlike    |
cranlike    | Node.js v18.16.0
```

**Comment by georgestagg** [comment]
My apologies, this was indeed due to a bad change that I made in the commit you mention. I've reverted the commit and (hopefully) fixed the issue with a new one (cc443a8). Please do test this in your environment and let me know.

I also expanded a comment in the `Makefile` to reinforce that the target in question is used for _both_ packaging and publication, to avoid the same issue happening again in future.

**Comment by jeroen** [comment]
Yes it seems fixed now. Thanks!
