### ISSUE TITLE
Next.js client side webr build error

### ISSUE THREAD

**Issue by WillemSleegers** [r-wasm/webr#282]
Hi,

I'm trying to create a WebR project using Next.js. I've seen the Next.js example [here](https://github.com/georgestagg/webr-nextjs-example/tree/main), but it only has a server-side example. 

When I try to create an example with a client-side example, I can get it to work locally but if I try to build I get various errors:

```
> meata-analysis@0.1.0 build
> next build

 ⚠ Compiled with warnings

./node_modules/webr/dist/webr.cjs
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/webr/dist/webr.cjs
./src/app/page.tsx

./node_modules/webr/dist/webr.cjs
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/webr/dist/webr.cjs
./src/app/page.tsx

 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (0/6)  [    ]
node:internal/event_target:1083
  process.nextTick(() => { throw err; });
                           ^
   Creating an optimized production build  .Error: Cannot find module '/Users/willem/GitHub/meata-analysis/.next/server/chunks/webr-worker.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:185:26)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
    at MessagePort.callbackTrampoline (node:internal/async_hooks:130:17)
    at [kOnExit] (node:internal/worker:304:5)
    at Worker.<computed>.onexit (node:internal/worker:229:20)
    at Worker.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.7.0
Static worker unexpectedly exited with code: 1 and signal: null
   Creating an optimized production build  .   Generating static pages (0/6)  [    ]
node:internal/event_target:1083
  process.nextTick(() => { throw err; });
                           ^
Error: Cannot find module '/Users/willem/GitHub/meata-analysis/.next/server/chunks/webr-worker.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:185:26)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
    at MessagePort.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.7.0
   Generating static pages (5/6)  [=   ] 

node:internal/event_target:1083
  process.nextTick(() => { throw err; });
                           ^
Error: Cannot find module '/Users/willem/GitHub/meata-analysis/.next/server/chunks/webr-worker.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:185:26)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
    at MessagePort.callbackTrampoline (node:internal/async_hooks:130:17)
    at [kOnExit] (node:internal/worker:304:5)
    at Worker.<computed>.onexit (node:internal/worker:229:20)
    at Worker.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

   Generating static pages (5/6)  [==  ] 

node:internal/event_target:1083
  process.nextTick(() => { throw err; });
                           ^
Error: Cannot find module '/Users/willem/GitHub/meata-analysis/.next/server/chunks/webr-worker.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:185:26)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
    at MessagePort.callbackTrampoline (node:internal/async_hooks:130:17)
    at [kOnExit] (node:internal/worker:304:5)
    at Worker.<computed>.onexit (node:internal/worker:229:20)
    at Worker.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}


> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/Users/willem/GitHub/meata-analysis/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/Users/willem/GitHub/meata-analysis/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:488:12)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  type: 'WorkerError'
}
   Generating static pages (5/6) on build  .   Generating static pages (0/6)  [    ] 
```

The code for this example can be found [here](https://github.com/WillemSleegers/meata-analysis).

Some advice on how to best set this up would be nice!

**Comment by bugzpodder** [comment]
If you are using `channelType.ServiceWorker` you'll need to define `serviceWorkerUrl` to `/` in `WebROptions` and follow https://docs.r-wasm.org/webr/latest/serving.html#sw-cdn (ie provide webr-worker.js and webr-serviceworker.js)

if you are using any other mode (that's not Automatic) it should just work.  channelType.Automatic of course depends on whether your site is crossOriginIsolated

**Comment by WillemSleegers** [comment]
I don't think I am using `channelType.Serviceworker` and I've checked whether the site is crossOriginIsolated.

**Comment by bugzpodder** [comment]
https://github.com/WillemSleegers/meata-analysis/blob/main/src/app/page.tsx#L6 try `serviceWorkerUrl: "/"`

**Comment by WillemSleegers** [comment]
Thanks for checking. I've removed `baseUrl` and set `serviceWorkerUrl` to `"/"`. It runs locally but I still get the same errors when I try to build (`nom run build`).

**Comment by WillemSleegers** [comment]
I think I fixed it by making a new client side (`"use client"`) component in which I load WebR. I then load that component into `page.tsx`, and then I don't get any the build error anymore.

(Before this I tried simply changing the `serviceWorkerUrl`, but that didn't work).

**Comment by bugzpodder** [comment]
I see.  if you ever want to get it working on server side, just lazily bootstrap, ie: 
`
const webR = null;
function getWebR() {
  webR = ...
}`

also checkout `ChannelType.PostMessage` where you don't need to include these worker files...

**Comment by WillemSleegers** [comment]
Interesting, thanks!

Closing this issue now because I fixed it.

**Comment by georgestagg** [comment]
> I think I fixed it by making a new client side ("use client") component in which I load WebR.

Yes, that should work. Glad you were able to get it up and running!

The Next.js (and other) example repos are a little out of date at this point, sorry about that. Hopefully I get a chance to update them soon.
