### ISSUE TITLE
PostMessage mode gives UnwindProtectException

### ISSUE THREAD

**Issue by bugzpodder** [r-wasm/webr#296]
i'll attempt a repo later, here is the error i see when executing multiple R scripts
```
WebR is using `PostMessage` communication channel, nested R REPLs are not available.
next-dev.js:20 UnwindProtectException: A non-local transfer of control occured during evaluation
    at eval (eval at addEmAsm (https://webr.r-wasm.org/v0.2.1/R.bin.js:1939:112104), <anonymous>:1:20)
    at runEmAsmFunction (https://webr.r-wasm.org/v0.2.1/R.bin.js:1939:309583)
    at _emscripten_asm_const_int (https://webr.r-wasm.org/v0.2.1/R.bin.js:1939:309662)
    at wasm://wasm/00010da6:wasm-function[82]:0x2af1
    at https://webr.r-wasm.org/v0.2.1/R.bin.wasm:wasm-function[894]:0x132851
    at wasm://wasm/00010da6:wasm-function[80]:0x2aaa
    at safeEval (blob:http://localhost:3001/1dbaf056-8aa4-4a72-92ce-fa532577b450:3226:68)
    at RCall.eval (blob:http://localhost:3001/1dbaf056-8aa4-4a72-92ce-fa532577b450:3623:25)
    at RFunction.exec (blob:http://localhost:3001/1dbaf056-8aa4-4a72-92ce-fa532577b450:3694:19)
    at callRObjectMethod (blob:http://localhost:3001/1dbaf056-8aa4-4a72-92ce-fa532577b450:4583:18)
```

**Comment by bugzpodder** [comment]
caused by https://github.com/r-wasm/webr/issues/280
